// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eq,hls_ip_2019_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.630000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=96,HLS_SYN_LUT=251,HLS_VERSION=2019_2}" *)

module eq (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
input  [31:0] b;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [64:0] mul_ln4_fu_44_p2;
reg   [64:0] mul_ln4_reg_116;
reg   [0:0] tmp_2_reg_121;
reg   [28:0] tmp_reg_127;
wire    ap_CS_fsm_state2;
wire  signed [31:0] sext_ln4_fu_40_p0;
wire  signed [31:0] mul_ln4_fu_44_p0;
wire  signed [31:0] tmp_2_fu_50_p1;
wire   [64:0] sub_ln4_fu_68_p2;
wire   [28:0] tmp_3_fu_73_p4;
wire  signed [31:0] sext_ln4_1_fu_83_p1;
wire  signed [31:0] sext_ln4_2_fu_87_p1;
wire   [31:0] select_ln4_fu_90_p3;
wire   [31:0] sub_ln4_1_fu_97_p2;
wire   [31:0] select_ln4_1_fu_103_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln4_reg_116[64 : 1] <= mul_ln4_fu_44_p2[64 : 1];
        tmp_2_reg_121 <= tmp_2_fu_50_p1[32'd31];
        tmp_reg_127 <= {{mul_ln4_fu_44_p2[64:36]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = (a + select_ln4_1_fu_103_p3);

assign mul_ln4_fu_44_p0 = sext_ln4_fu_40_p0;

assign mul_ln4_fu_44_p2 = ($signed(mul_ln4_fu_44_p0) * $signed(65'h19999999A));

assign select_ln4_1_fu_103_p3 = ((tmp_2_reg_121[0:0] === 1'b1) ? sub_ln4_1_fu_97_p2 : sext_ln4_2_fu_87_p1);

assign select_ln4_fu_90_p3 = ((tmp_2_reg_121[0:0] === 1'b1) ? sext_ln4_1_fu_83_p1 : sext_ln4_2_fu_87_p1);

assign sext_ln4_1_fu_83_p1 = $signed(tmp_3_fu_73_p4);

assign sext_ln4_2_fu_87_p1 = $signed(tmp_reg_127);

assign sext_ln4_fu_40_p0 = b;

assign sub_ln4_1_fu_97_p2 = (32'd0 - select_ln4_fu_90_p3);

assign sub_ln4_fu_68_p2 = (65'd0 - mul_ln4_reg_116);

assign tmp_2_fu_50_p1 = b;

assign tmp_3_fu_73_p4 = {{sub_ln4_fu_68_p2[64:36]}};

always @ (posedge ap_clk) begin
    mul_ln4_reg_116[0] <= 1'b0;
end

endmodule //eq
